config/routes.rb
Rails.application.routes.draw do

  get '/students' => 'dashboard#index'
  get 'dashboard/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :students
    resources :reviews
    resources :teachers
    resources :teaches
    resources :subjects
    resources :departments
    resources :schools

    # Page Routing
    %w[index about contact].each do |page|
        get page, controller: 'pages', action: page
    end

    # Page Root
    root to: "pages#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < InheritedResources::Base

  private

    def department_params
      params.require(:department).permit(:department_name, :chair_name, :about_text, :school_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base

  private

    def review_params
      params.require(:review).permit(:subject, :review_text, :star_rating, :recommended, :teaching_style, :status, :votes, :teacher_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < InheritedResources::Base

  private

    def school_params
      params.require(:school).permit(:school_name, :dean_name, :about_text)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < InheritedResources::Base

  private

    def subject_params
      params.require(:subject).permit(:subject_name, :subject_catalog_number, :about_text, :department_id)
    end
end

app/controllers/teaches_controller.rb
class TeachesController < InheritedResources::Base

  private

    def teach_params
      params.require(:teach).permit(:teacher_id, :subject_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/departments/_form.html.erb
<%= simple_form_for(@department) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :department_name %>
    <%= f.input :chair_name %>
    <%= f.input :about_text %>
    <%= f.input :school_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<h1>Listing departments</h1>

<table>
  <thead>
    <tr>
      <th>Department name</th>
      <th>Chair name</th>
      <th>About text</th>
      <th>School</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.department_name %></td>
        <td><%= department.chair_name %></td>
        <td><%= department.about_text %></td>
        <td><%= department.school_id %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department name:</strong>
  <%= @department.department_name %>
</p>

<p>
  <strong>Chair name:</strong>
  <%= @department.chair_name %>
</p>

<p>
  <strong>About text:</strong>
  <%= @department.about_text %>
</p>

<p>
  <strong>School:</strong>
  <%= @department.school_id %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>