config/routes.rb
Rails.application.routes.draw do

  get '/students' => 'dashboard#index'
  get 'dashboard/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :students
    resources :reviews
    resources :teachers
    resources :teaches
    resources :subjects
    resources :departments
    resources :schools

    # Page Routing
    %w[index about contact].each do |page|
        get page, controller: 'pages', action: page
    end

    # Page Root
    root to: "pages#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base

  private

    def review_params
      params.require(:review).permit(:subject, :review_text, :star_rating, :recommended, :teaching_style, :status, :votes, :teacher_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < InheritedResources::Base

  private

    def school_params
      params.require(:school).permit(:school_name, :dean_name, :about_text)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < InheritedResources::Base

  private

    def subject_params
      params.require(:subject).permit(:subject_name, :subject_catalog_number, :about_text, :department_id)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < InheritedResources::Base

  private

    def teacher_params
      params.require(:teacher).permit(:first_name, :middle_initial, :last_name, :teaching_style)
    end
end

app/controllers/teaches_controller.rb
class TeachesController < InheritedResources::Base

  private

    def teach_params
      params.require(:teach).permit(:teacher_id, :subject_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :school_name %>
    <%= f.input :dean_name %>
    <%= f.input :about_text %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>Listing schools</h1>

<table>
  <thead>
    <tr>
      <th>School name</th>
      <th>Dean name</th>
      <th>About text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.school_name %></td>
        <td><%= school.dean_name %></td>
        <td><%= school.about_text %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School name:</strong>
  <%= @school.school_name %>
</p>

<p>
  <strong>Dean name:</strong>
  <%= @school.dean_name %>
</p>

<p>
  <strong>About text:</strong>
  <%= @school.about_text %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

app/views/subjects/_form.html.erb
<%= simple_form_for(@subject) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject_name %>
    <%= f.input :subject_catalog_number %>
    <%= f.input :about_text %>
    <%= f.input :department_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<h1>Listing subjects</h1>

<table>
  <thead>
    <tr>
      <th>Subject name</th>
      <th>Subject catalog number</th>
      <th>About text</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subject_name %></td>
        <td><%= subject.subject_catalog_number %></td>
        <td><%= subject.about_text %></td>
        <td><%= subject.department_id %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject name:</strong>
  <%= @subject.subject_name %>
</p>

<p>
  <strong>Subject catalog number:</strong>
  <%= @subject.subject_catalog_number %>
</p>

<p>
  <strong>About text:</strong>
  <%= @subject.about_text %>
</p>

<p>
  <strong>Department:</strong>
  <%= @subject.department_id %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>

app/views/teachers/_form.html.erb
<%= simple_form_for(@teacher) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :middle_initial %>
    <%= f.input :last_name %>
    <%= f.input :teaching_style %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Middle initial</th>
      <th>Last name</th>
      <th>Teaching style</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.middle_initial %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.teaching_style %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @teacher.first_name %>
</p>

<p>
  <strong>Middle initial:</strong>
  <%= @teacher.middle_initial %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Teaching style:</strong>
  <%= @teacher.teaching_style %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>

app/views/teaches/_form.html.erb
<%= simple_form_for(@teach) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :teacher_id %>
    <%= f.input :subject_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/teaches/edit.html.erb
<h1>Editing teach</h1>

<%= render 'form' %>

<%= link_to 'Show', @teach %> |
<%= link_to 'Back', teaches_path %>

app/views/teaches/index.html.erb
<h1>Listing teaches</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teaches.each do |teach| %>
      <tr>
        <td><%= teach.teacher_id %></td>
        <td><%= teach.subject_id %></td>
        <td><%= link_to 'Show', teach %></td>
        <td><%= link_to 'Edit', edit_teach_path(teach) %></td>
        <td><%= link_to 'Destroy', teach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teach', new_teach_path %>

app/views/teaches/new.html.erb
<h1>New teach</h1>

<%= render 'form' %>

<%= link_to 'Back', teaches_path %>

app/views/teaches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @teach.teacher_id %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @teach.subject_id %>
</p>

<%= link_to 'Edit', edit_teach_path(@teach) %> |
<%= link_to 'Back', teaches_path %>