config/routes.rb
Rails.application.routes.draw do

  get '/students' => 'dashboard#index'
  get 'dashboard/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :students
    resources :reviews
    resources :teachers
    resources :teaches
    resources :subjects
    resources :departments
    resources :schools

    # Page Routing
    %w[index about contact].each do |page|
        get page, controller: 'pages', action: page
    end

    # Page Root
    root to: "pages#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base

  private

    def review_params
      params.require(:review).permit(:subject, :review_text, :star_rating, :recommended, :teaching_style, :status, :votes, :teacher_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < InheritedResources::Base

  private

    def school_params
      params.require(:school).permit(:school_name, :dean_name, :about_text)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < InheritedResources::Base

  private

    def subject_params
      params.require(:subject).permit(:subject_name, :subject_catalog_number, :about_text, :department_id)
    end
end

app/controllers/teaches_controller.rb
class TeachesController < InheritedResources::Base

  private

    def teach_params
      params.require(:teach).permit(:teacher_id, :subject_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :review_text %>
    <%= f.input :star_rating %>
    <%= f.input :recommended %>
    <%= f.input :teaching_style %>
    <%= f.input :status %>
    <%= f.input :votes %>
    <%= f.input :teacher_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Review text</th>
      <th>Star rating</th>
      <th>Recommended</th>
      <th>Teaching style</th>
      <th>Status</th>
      <th>Votes</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.subject %></td>
        <td><%= review.review_text %></td>
        <td><%= review.star_rating %></td>
        <td><%= review.recommended %></td>
        <td><%= review.teaching_style %></td>
        <td><%= review.status %></td>
        <td><%= review.votes %></td>
        <td><%= review.teacher_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @review.subject %>
</p>

<p>
  <strong>Review text:</strong>
  <%= @review.review_text %>
</p>

<p>
  <strong>Star rating:</strong>
  <%= @review.star_rating %>
</p>

<p>
  <strong>Recommended:</strong>
  <%= @review.recommended %>
</p>

<p>
  <strong>Teaching style:</strong>
  <%= @review.teaching_style %>
</p>

<p>
  <strong>Status:</strong>
  <%= @review.status %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @review.votes %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @review.teacher_id %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>