config/routes.rb
Rails.application.routes.draw do

  get '/students' => 'dashboard#index'
  get 'dashboard/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :students
    resources :reviews
    resources :teachers
    resources :teaches
    resources :subjects
    resources :departments
    resources :schools

    # Page Routing
    %w[index about contact].each do |page|
        get page, controller: 'pages', action: page
    end

    # Page Root
    root to: "pages#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teach.rb
class Teach < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < InheritedResources::Base

  private

    def review_params
      params.require(:review).permit(:subject, :review_text, :star_rating, :recommended, :teaching_style, :status, :votes, :teacher_id)
    end
end

app/controllers/schools_controller.rb
class SchoolsController < InheritedResources::Base

  private

    def school_params
      params.require(:school).permit(:school_name, :dean_name, :about_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/teaches_helper.rb
module TeachesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectblue</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <center>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </center>


  <div align = "right">

        <% if student_signed_in? %>

            <%= link_to('Dashboard', :controller => "dashboard", :action => "index") %> :
            <%= link_to('Logout', destroy_student_session_path, :method => :delete) %> :
            <br>
            Reviews :
            Professors :

        <% else %>

            <%= link_to('Home', root_path) %> :
            <%= link_to('Sign up', new_student_registration_path ) %> :
            <%= link_to('Login?', new_student_session_path)  %>

        <% end %>



  </div>



  <%= yield %>

<footer>

</footer>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
<h1>Project Blue</h1>
<p></p>